spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/dsy
    username: postgres
    password: 2007
    driver-class-name: org.postgresql.Driver
  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.example.myapp.model
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
